workspace = { members = ["example/simple"] }

[package]
name = "mysh"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
colored = "2.1.0"
ctrlc = "3.4.2"
futures = "0.3.30"
indoc = "2.0.4"
serde = "1.0.195"
serde-reflection = "0.3.6"
serde_derive = "1.0.195"
serde_json = "1.0.111"
mysh_derive = { path = "./derive" }
thiserror = "1.0.56"
