[package]
name = "mysh_derive"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
serde = "1.0.195"
serde-reflection = "0.3.6"
serde_json = "1.0.111"
syn = "2.0.48"
quote = "1.0.35"
proc-macro2 = "1.0.78"

[lib]
proc-macro = true
